export const LOGIN_USER = 'LOGIN_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_TESTIMONIALS = 'GET_TESTIMONIALS';
export const POST_TESTIMONIAL = 'POST_TESTIMONIAL';
export const DELETE_TESTIMONIAL = 'DELETE_TESTIMONIAL';
