export const LOGIN_USER = 'LOGIN_USER';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_TESTIMONIALS = 'GET_TESTIMONIALS';
export const LOADING_TESTIMONIALS = 'LOADING_TESTIMONIALS';
export const ADD_TESTIMONIAL = 'ADD_TESTIMONIAL';
export const ERR_TESTIMONIAL = 'ERR_TESTIMONIAL';
export const DEL_TESTIMONIAL = 'DEL_TESTIMONIAL';
